#!/bin/bash
modules_dir="/var/www/html/freepbx/admin/modules/"
m="/usr/src/nethvoice/modules/recallonbusy.tar.gz"
filename=$(basename "$m")
name="${filename%.tar.gz}"

# Extract module
if [ ! -d $modules_dir$name ]; then
    mkdir -p $modules_dir$name
else
    rm -fr $modules_dir$name/*
fi
tar xf $m -C $modules_dir$name --strip-components 1
chown -R asterisk:asterisk $modules_dir$name

# Install module
/usr/bin/scl enable rh-php56 -- fwconsole moduleadmin install recallonbusy

# Apply config
/usr/bin/scl enable rh-php56 -- fwconsole r

